name:                code-gen-tutori
version:             0.1.0.0
github:              "mjgajda/code-gen-tutori"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@migamake.com"
copyright:           "AllRightsReserved"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mjgajda/code-gen-tutori#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- template-haskell
- cassava
- bytestring
- haskell-src-match
- hint
- run-haskell-module

library:
  source-dirs: src

executables:
  ex1:
    main: app/ex1/Main.hs
  ex3:
    main: app/ex2/Main.hs

tests:
  ex2:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - code-gen-tutori
